# kivitendo-Hilfe

Willkommen bei der [kivitendo](http://www.kivitendo.org/)-Hilfe. Dies ist die Startseite.

## Externe Hilfequellen

Es gibt mehrere externe Hilfequellen, die Sie kontaktieren können:

* [das Forum](https://forum.kivitendo.de:32443/)
* [den Bugtracker](http://redmine.kivitendo-premium.de/projects/forum/issues)
* [die Mailinglisten](http://www.kivitendo.org/community/mailinglisten.html)
