# Hauptüberschrift

Dieser Abschnitt enthält Informationen zum Anlegen neuer oder Bearbeiten bestehender Artikel in den Stammdaten.

Doppelte Zeilenumbrüche sollten einen neuen Absatz einleiten.

Einzelne Zeilenumbrüche im Quelltext
sollten auch in der Ausgabe
einen Zeilenumbruch erzeugen.

## Kleinere Überschrift
Eine Leerzeile nach einer Überschrift sollte nicht nötig sein.

Eine Leerzeile vor einer Überschrift sollte nicht nötig sein.
## Auch eine Überschrift

Bauen wir eine Aufzählungsliste:

* Punkt eins
* Punkt zwei
* Noch ein Punkt

Und nun eine mit Nummerierung:

1. Weil ich das toll finde.
2. Weil ich immer Recht habe.
3. Mehr Begründungen werden selbstverständlich dann auch nicht benötigt.

Jezt folgt ein Block, der besonders hervorgehoben werden soll:

==Achtung!
Dies ist die öffentliche Bekanntmachung, dass kivitendo toll ist!==

Jut. Nun dann. Was brauchen wir noch? Richtig, eine Tabelle!

| Film/Serie | Zitat |
|--------|--------|
| Battlestar Galactica |  So say we all! |
| Dirty Dancing | Ich habe eine Wassermelone getragen. |
| Ghostbusters | Er schleimte mich voll. |

Textauszeichnung[^1] ist auch wichtig. Reden wir über *kursiv* oder **fett** oder gar `typesetter`? Wer weiß das schon so genau!

Externe Links wie z.B. zur [kivitendo-Homepage](http://www.kivitendo.org/) sind auch wichtig.

Codeblöcke sind interessant. Diese werden eingerückt:

    package Sparta;
    sub new {
      say "This is ", $_[0], "!";
    }

Das geht aber auch anders:

```
package Sparta;
sub new {
  say "This is ", $_[0], "!";
}
```

Alrighty.

Ein Bild sagt mehr als ein besoffener Hund.

![Ein Bild, ein Bild](image/kivitendo.png)

[^1]: Stay away from da Voodoo, mon!
